################################################################################
#
#  This file is part of SplashSync Project.
#
#  Copyright (C) Splash Sync <www.splashsync.com>
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
#  For the full copyright and license information, please view the LICENSE
#  file that was distributed with this source code.
#
#  @author Bernard Paquier <contact@splashsync.com>
#
################################################################################

################################################################
# Set any variables we need
variables:
  MYSQL_HOST:               mysql
  MYSQL_ROOT_PASSWORD:      myrootpassword
  MYSQL_USER:               magento
  MYSQL_PASSWORD:           magento
  MYSQL_DATABASE:           magento
  MAGENTO_LANGUAGE:         en_US
  MAGENTO_TIMEZONE:         Europe/Paris
  MAGENTO_DEFAULT_CURRENCY: EUR
  MAGENTO_URL:              http://localhost
  MAGENTO_BACKEND_FRONTNAME:  admin
  MAGENTO_USE_SECURE:       0
  MAGENTO_BASE_URL_SECURE:  0
  MAGENTO_USE_SECURE_ADMIN: 0
  MAGENTO_ADMIN_FIRSTNAME:  Admin
  MAGENTO_ADMIN_LASTNAME:   MyStore
  MAGENTO_ADMIN_EMAIL:      admin@example.com
  MAGENTO_ADMIN_USERNAME:   admin
  MAGENTO_ADMIN_PASSWORD:   magento2admin
  COMPOSER_MEMORY_LIMIT:    -1

################################################################
# Defined Pipeline Stages
stages:
  - docker
  - tests
#  - deploy

################################################################
# Functional Tests
################################################################

core_tests:
    image:      alexcheng/magento2
    stage:      tests
#    retry:      2
    tags:
      - Dedicated
    services:
      - name: mysql:5.7

    ################################################################################
    # Install & Configure Environment
    before_script:
      ################################################################################
      - echo "\033[32m BEFORE --> Install Magento 2          \033[0m"
      - install-magento
      ################################################################################
      - echo "\033[32m BEFORE --> Install Splash             \033[0m"
      - cat /builds/SplashSync/Magento2/scripts/install-phpunit.sh | bash
      - cat /builds/SplashSync/Magento2/scripts/install-dev-module.sh | bash
      ################################################################################
      - echo "\033[32m BEFORE --> Setup Magento 2            \033[0m"
      - cat /builds/SplashSync/Magento2/scripts/setup-magento.sh | bash
      - cat /builds/SplashSync/Magento2/scripts/compile-magento.sh | bash
    ################################################################################
    # Run Test Script
    script:
      - cd /var/www/html
      - php bin/magento config/show
      ################################################################################
      - echo "\033[32m UNIT TESTS --> Init & Local             \033[0m"
      - php /usr/bin/phpunit --testsuite=Local
      ################################################################################
      - echo "\033[32m UNIT TESTS --> Full                     \033[0m"
      - php /usr/bin/phpunit --testsuite=Core
    ################################################################################
    # Run After Script
#    after_script:


#################################################################
## Build Documentation
#################################################################
#pages:
#    image:      registry.gitlab.com/splashsync/php-console:pages
#    stage:      deploy
#    retry:      2
#    tags:
#      - Dedicated
#    ################################################################################
#    # Run Test Script
#    script:
#      # Run Composer to Build Dependencies
#      - curl -s https://raw.githubusercontent.com/BadPixxel/Php-Sdk/main/ci/composer.sh  | bash
#      # Build Documentation
#      - php vendor/bin/grumphp run --tasks=build-docs
#    artifacts:
#        paths:
#            - public

################################################################
# Build Docker Images for Testing
################################################################
docker:
  #    when:       manual
  stage:      docker
  image:      docker:stable
  tags:       ['Dedicated-Docker']
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - echo "Build & Upload Docker Image"
    # Connect Docker to DockerHub
    - docker login -u splashsync -p $DOCKER_HUB_TOKEN
    # Build & Upload Splash All Docker Images
    - docker build -t splashsync/magento2:2.4-php7.2 -f docker/magento/mage-2.4-php7.2.Dockerfile docker/magento
    - docker push splashsync/magento2:2.4-php7.2
  except:
    - schedules
