
splash:

  ################################################################################
  # Configure Splash Bundle Parameters Cache
  # Cache is Enabled by Default to Store Custom Connectors Configuration
  # If disabled, configuration must be store in Static, on connections section
  ################################################################################
  #    cache:
  #        enabled: false
  #        lifetime: 10

  # Allow Notifications for Generic Users
  notify: ["ROLE_USER"]

  ################################################################################
  # List of Available Connector Connections
  ################################################################################

  connections:

    ########################################################################
    # Magento Latest
    latest:
      id:                 ThisIsMagento2Key
      key:                ThisTokenIsNotSoSecretChangeIt
      name:               Magento 2 Latests
      host:               false
      connector:          soap
      config:
        WsIdentifier:       ThisIsMagento2Key
        WsEncryptionKey:    ThisTokenIsNotSoSecretChangeIt
        WsHost:             http://latest.magento2.local
        WsPath:             /splash/ws/soap
